### ISSUE TITLE
Add useFiltered func

### ISSUE THREAD

**Issue by KingPepito** [alexandre-lelain/js-extra#4]
Add a function that is allowing to manipulate each element that have passed the classic filter function. 

You might also consider it as a map() that manipulate each element followed by a compact() that is keeping only transformed values.

A sample use case might look like :

```javascript
const array = [1, 2, 5, 15, 3 ,9]
// [4, 14, 8]
const arrayFiltered = useFiltered(array, n => n > 3, n => n - 1)
```

**Comment by alexandre-lelain** [comment]
Hello,

Thanks a lot for your issue. This can be a good function. I'd suggest to add a parameter to add a `compact-like` action if the user wants to remove falsy values from the array.

Also, I suggest to go for `redesign` regarding the function name. `useX` is a pattern for hooks, and `useFiltered` doesn't sound enough specific in my opinion.

**Comment by alexandre-lelain** [comment]
Done in https://github.com/alexandre-lelain/js-extra/commit/08decb2fc0eb7ff5f08f62a2bd8c2967b3386f18
